config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups do
    member do
      post :join
      post :quit
    end

  resources :posts
end

namespace :account do
  resources :groups
  resources :posts
end

  root 'groups#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_many :group_relationships
  has_many :members, through: :group_relationships, source: :user
  validates :title, presence: true


  mount_uploader :image, ImageUploader
end

app/models/group_relationship.rb
class GroupRelationship < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :content, presence: true

  scope :recent, -> { order("created_at DESC")}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
  has_many :posts
  has_many :group_relationships
  has_many :participated_groups, :through => :group_relationships, :source => :group

  def is_member_of?(group)
    participated_groups.include?(group)
  end

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end

end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = current_user.posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy]
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group .user = current_user
    if @group.save
       current_user.join!(@group)
       redirect_to groups_path
     else
       render :new
     end
  end

  def update
    if @group.update(group_params)
       redirect_to groups_path, notice: "Update Success"
    else
       render :edit
    end
  end

  def destroy
    @group.destroy
    flash[:alert] = "Group deleted"
    redirect_to groups_path
  end

  def join
    @group = Group.find(params[:id])

    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = "Add to My Favorites!~"
    else
      flash[:warning] = "The Review's already in My Favorites!~"
    end

    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])

    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:alert] = "Remove from My Favorites!~"
    else
      flash[:warning] ="It's already added to My Favorites!~"
    end

    redirect_to group_path(@group)
  end

  private

  def find_group_and_check_permission
    @group = Group.find(params[:id])

    if current_user != @group.user
      redirect_to root_path, alert: "You have no permission."
    end
  end


  def group_params
    params.require(:group).permit(:title, :description, :image)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create]

  def new
    @group = Group.find(params[:group_id])
    @post = Post.new
  end

  def create
    @group = Group.find(params[:group_id])
    @post = Post.new(post_params)
    @post.group = @group
    @post.user = current_user

    if @post.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end


  private

  def post_params
    params.require(:post).permit(:content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "good morning! 哈哈！～"
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_group_description(group)
    simple_format(group.description)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer id="footer-navigation" class="container" style="margin-top: 100px;">
    <p class="text-center">
        <br>Design by Ling Min Chen
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Movie Review</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                  <li><%= link_to("sign up", new_user_registration_path) %> </li>
                  <li><%= link_to("log in", new_user_session_path) %></li>
                  <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.email %>
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li> <%= link_to("My Favorites", account_groups_path) %></li>
                      <li> <%= link_to("My Posts", account_posts_path) %></li>
                      <li class="divider"> </li>
                      <li> <%= link_to("sign out", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                  <% end %>
                  
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
    <%= f.input :image, as: :file %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/groups/_group_item.html.erb
<tr>

  <td><%= link_to(group.title, group_path(group)) %></td>
  <td><%= render_group_description(group) %></td>
  <td><%= group.user.email %></td>
  <td><%= group.created_at %></td>
  <td>

    <% if current_user && current_user == group.user %>
      <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
      <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default",
                  method: :delete, data: { confirm: "Are you sure?" } )%>
    <% end %>

  </td>

</tr>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>Edit Review</h2>
    <hr>

    <%= simple_form_for @group do |f| %>
      <div class="form-group">
        <%= f.input :title, input_html: { class: "form-control"} %>
        <%= f.input :description, input_html: { class: "form-control"} %>
        <% if @group.image.present? %>
        <span>目前图片</span>
        <%= image_tag(@group.image.thumb.url, class: "thumbnail")%>
        <% end %>
        <%= f.input :image, as: :file %>
      </div>
      <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
    <% end %>
</div>

app/views/groups/index.html.erb
<div class="col-md-4 col-offset-4">
  <h1 id="home-title">最新影评</h1>
</div>
<br/>

<div class="col-md-12">
  <div class="row">
    <div class="well" id="home-well"></div>
  </div>
</div>

<div class="col-md-12">
  <div class="group">
    <div class="dropdown clearfix">  </div>
    <div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        All genres
          <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
        <li><a href="#">Action</a></li>
        <li><a href="#">Adventure</a></li>
        <li><a href="#">Animation</a></li>
        <li><a href="#">Biopic</a></li>
        <li><a href="#">Comedy</a></li>
        <li><a href="#">Crime</a></li>
        <li><a href="#">Documentary</a></li>
        <li><a href="#">Drama</a></li>
        <li><a href="#">Family</a></li>
        <li><a href="#">Fantasy</a></li>
        <li><a href="#">Horro</a></li>
        <li><a href="#">Horror</a></li>
        <li><a href="#">Music</a></li>
        <li><a href="#">Mystery</a></li>
        <li><a href="#">Romance</a></li>
        <li><a href="#">Sc-Fi</a></li>
        <li><a href="#">Sci-Fi</a></li>
        <li><a href="#">Sports</a></li>
        <li><a href="#">Thiller</a></li>
        <li><a href="#">Thriller</a></li>
        <li><a href="#">War</a></li>
        <li><a href="#">Western</a></li>
      </ul>
      <div class="btn-group">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
          Order
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
          <li><a href="#">Latest</a></li>
          <li><a href="#">Rating</a></li>
          <li><a href="#">Title</a></li>
          <li><a href="#">Classification</a></li>
        </ul>
      </div>
      <%= link_to("Post a Movie Review", new_group_path, class: "btn btn-success pull-right") %>
    </div>
  </div>
</div>
<br/><br/><br/>


  <!-- <div>
    <%= link_to("Post a Movie Review", new_group_path, class: "btn btn-success pull-right") %>
  </div>
  <br/>
  <hr/> -->
  <!-- <table class="table table-boldered">


    <tbody>
       <%= render :partial => "group_item", :collection => @groups, :as => :group %>
    </tbody>
  </table> -->

<div class="col-md-8 group-content clearfix">
  <% @groups.each do |group| %>
    <div class="row" id="group-item">
      <div class="col-md-2">
        <% if !group.image.present? %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "img-thumbnail img-responsive")%>
          <% else %>
          <%= image_tag(group.image.thumb.url, class: "img-thumbnail img-responsive")%>
          <% end %>
        </div>
        <div class="col-md-10 clearfix">
          <h4 class="group-title well"><%= group.title %>  <small>(<%= group.user.email %>)</small> </h4>
          <div class="group-description" id="group-description"><%= group.description %></div>
          <p class="pull-right" id="group-created_at"><small><%= group.created_at.to_s(:db) %></small></p>
        </div>
      </div>

  <% end %>
      </div>
  <div class="col-md-4">
    <div id="right-text">
    <p>如果你觉得一篇评论对你有帮助，请你点击“有用”。你的投票直接决定哪些评论出现在豆瓣首页和“豆瓣最受欢迎的评论”里，以及在书、电影和音乐介绍页里评论的排序。所有“没用”的点击都是匿名的。</p>
    <div class="rrs">
      <i class="fa fa-rss"></i>
      <%= link_to '订阅最新上线的电影影评～', '#'%>
    </div>
    </div>
  </div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>Create New Review</h2>

    <hr>

    <%= render "form" %>

</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">

    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@group) %>
        <%= link_to(content_tag(:span, "", :class => "fa fa-heart"), quit_group_path(@group), method: :post, class: "btn btn-pull-right") %>

          <% else %>
        <%= link_to(content_tag(:span, "", :class => "fa fa-heart-o"), join_group_path(@group), method: :post, class: "btn btn-pull-right") %>

          <% end %>
    </span>
    <%= link_to("Write a Post", new_group_post_path(@group), class: "btn btn-link pull-right")%>
    <% if current_user && current_user == @group.user %>
    <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right")%>
<% end %>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>

  <table class="table">
    <thead>
      <tr>
         <th> Comments </th>
         <th> Creator </th>
         <th> Last Update </th>
       </tr>
     </thead>
     <tbody>
       <% @posts.each do |post| %>
         <tr>
           <td><%= post.content %></td>
           <td><%= post.user.email %></td>
           <td><%= post.created_at %></td>
         </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= will_paginate @posts %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails105</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid">
      <div class="row">
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>

          <div class="col-md-2">
            <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
               <li class="active"><%= link_to("Top Comments", groups_path ) %> </li>
               <li class="active"><%= link_to("Newest first", groups_path ) %> </li>
            </ul>
          </div>

          <div class="col-md-10">
            <%= yield %>
          </div>
      </div>
      <div class="row">
        <%= render "common/footer" %>
      </div>
    </div>

  </body>
</html>

app/views/posts/new.html.erb
<h2 class="text-center"> Create Comment </h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group,@post] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>